### PR TITLE
Update pacextractor

### PR DESCRIPTION
**Pull request by HemanthJabalpuri**
Use pacextractor from https://github.com/HemanthJabalpuri/pacextractor/blob/9d7690187006e029867016af9c6620c565c3428f/python/pacExtractor.py for supporting newer .pac files that are greater than 4GiB

### CODE REVIEW

**Comment by HemanthJabalpuri** [comment]
@deadman96385

**Comment by HemanthJabalpuri** [comment]
Test firmware is available at https://mirrors.lolinet.com/firmware/moto/java/official/RETAIL/JAVA_RETAIL_P352CE_PVT_11.0_64B_CFC_68-29-2.00-00_FLASHER_sign_20220123131534.zip (Moto G20)

**Comment by deadman96385** [comment]
Tested it out on some older ones, seems to work fine. Thank you for the contribution!

**Comment by HemanthJabalpuri** [comment]
Thanks. Below are the firmwares I have tested

Test firmwares are

**BP_R1.0.0**
- [Moto E20](https://mirrors.lolinet.com/firmware/motorola/aruba/official/RETEU/XT2155-3_ARUBA_RETEU_11_RON31.267-12_2201_20220118_user_SIGN_025.zip)
- [JingPad A1/C1](https://forum.jingos.com/t/how-to-flash-android-rom-on-jingpad-a1-c1/2716)

**BP_R2.0.1**
- [Moto G20](https://mirrors.lolinet.com/firmware/moto/java/official/RETAIL/JAVA_RETAIL_P352CE_PVT_11.0_64B_CFC_68-29-2.00-00_FLASHER_sign_20220123131534.zip)
- [Lenovo A7](https://mirrors.lolinet.com/firmware/lenovo/l19111/L19111_CN_OPEN_USER_SC9863_P_DRV_11.0.409_ST_210308.zip)


Closing my issue too #19

**Pull request merged**
